name: Python Downloader
on:
  workflow_dispatch: # 手動実行用

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: コードを取得
        uses: actions/checkout@v3

      - name: Python準備
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 必要な道具をインストール
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp requests

      - name: Python実行
        run: python main.py  # ここでファイル名が間違っているとエラー2が出ます

      - name: 保存
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "ファイルを保存しました" || echo "変更なし"
          git push
